### ISSUE TITLE
expose ability to replace state

### ISSUE THREAD

**Issue by Guria** [christianalfoni/addressbar#4]
**variant 1**

``` js
addressbar.replace(newUrl);
```

**variant 2**

``` js
addressbar.replaceNext();
addressbar.value = newUrl;
```

**variant 3**

``` js
addressbar.value = '!' + newUrl;
```

**Comment by christianalfoni** [comment]
Thanks for the suggestions and thinking "out of the box" :-)

I have a feeling we just have to expose a method for this, as your first suggestion. But lets play with this some more first.

``` js
addressbar.value = {
  url: newUrl,
  replace: true
};
```

Which could also be used to:

``` js
addressbar.value = {
  url: newUrl,
  replace: true,
  hash: true,
  query: myQuery
};
```

I kinda like this, as it opens up even new doors. What do you think?

**Comment by Guria** [comment]
Hmm. I like this. Should we still support string values?

**Comment by christianalfoni** [comment]
Hm, good question. My initial thought is "yes". That is like default behaviour. But since this is somewhat a magic input it also supports an object as a value :-)

**Comment by Guria** [comment]
There is another question: `console.log(addressbar.value)`?

**Comment by Guria** [comment]
Ok, I think then `addressbar.value` is string by default, but accepts object in setter?

**Comment by christianalfoni** [comment]
That is also a good point. I think actually we should return the string now. To avoid any migration issues. Then we get some experience with it and can make a better decision on maybe stripping out strings completely or other alternatives.

**Comment by Guria** [comment]
@christianalfoni add me as colaborator so I could push a new branch

**Comment by Guria** [comment]
@christianalfoni I think I'll leave this task for you. I am afraid I will not write adequate tests in this project in short time.

``` js
      if (typeof value === "object") {
        doReplace = !!value.replace;
        value = value.url;
      }
```

**Comment by christianalfoni** [comment]
Cool, lets conclude with allowing an object to be set like this:

``` js
addressbar.value = {
  value: url,
  replace: true
}
```

To force replacing the url. This allows for expanding and does not require any migration path. I will make this part of the next `cerebral-router` release package :-)

**Comment by Guria** [comment]
we need it before router new relese so we could test routers redirect

**Comment by christianalfoni** [comment]
Jup, will do that

**Comment by christianalfoni** [comment]
Okay, got it running with test and updated documentation

**Comment by christianalfoni** [comment]
released
